name: Build
 
on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop
 
jobs:
  setup:
    name: Setup NodeJS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

  build: 
    name: Build project
    needs: setup
    runs-on: ubuntu-latest
    working-directory: nexus-bot
    steps:
      - name: build
        run: npm run build-ts
 
  lint:
    name: Linter check
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: npm run lint
